### ISSUE TITLE
Add button for season 7

### ISSUE THREAD

**Issue by denishamann** [denishamann/arena-stats-tbc-visualizer#10]
Report from Neph on Curseforge:

Who would have thought that the addon survive beyond tbc :p We now have to add a season 7+ button.

> Hello!
> 
> I am having an issue with this season 7 seeing my stats. When I export my arena stats to the website it only says season 6+, with no separate tab for season 7. 
> 
> Therefore I can't see my stats for season 7 separately (only season 6+ as in season 6 and 7 combined). Is there anyway I can fix this? Thanks.
> -Neph

@Simon3 Could you take care of this?

**Comment by Simon3** [comment]
Sure
```
Season 6 ended on May 29, 10:00 p.m. PDT (1:00 a.m. EDT)
Season 7 started with the June 20 regional maintenance
```
Will push an update in the next days

**Comment by Simon3** [comment]
See https://github.com/denishamann/arena-stats-visualizer/pull/11
