### ISSUE TITLE
New filtering features

### ISSUE THREAD

**Issue by SaneSL** [denishamann/arena-stats-tbc-visualizer#8]
Hey,

I'm sometimes using this app, but the filtering could use some improvements. This is something I could work on and submit a pull request later on. I have some ideas and if you could comment on them.

- Allow results to be filterered by team. The current statistics are kinda useless if you swapped a team mid season.
- Allow results to be filtered with a date range.
- Selecting a team comp could show match history againts that team. 

Thanks

**Comment by denishamann** [comment]
Hello SaneSL, any PR is welcome, @Simon3 will probably take care of the review since he wrote most of the visualiser.

Thank you!

**Comment by Simon3** [comment]
Hello, these are great ideas. I had actually already thought of adding the possibility of filtering results by player name (teammate or even enemies, e.g. what is my winrate against X), but I'm not playing the game anymore so no real motivation to work on it anymore. But I would be happy to review any PR!

**Comment by SaneSL** [comment]
Sounds good! I will close this issue and submit a PR in time 😄
